-- Ambassador wallet credit system:
-- - Earn: tracked from ambassador code redemptions (commission_amount_eur).
-- - Spend: ambassadors can use accrued commission as checkout credit.
-- Idempotent migration, safe to run multiple times.

alter table public.ambassador_redemptions
  add column if not exists commission_amount_eur numeric;

-- Backfill commission amounts for legacy rows (best effort with current code pct).
update public.ambassador_redemptions r
set commission_amount_eur = round(coalesce(r.order_total_eur, 0) * coalesce(c.commission_pct, 0) / 100, 2)
from public.ambassador_codes c
where upper(c.code) = upper(r.code)
  and r.commission_amount_eur is null;

create table if not exists public.ambassador_wallet_spends (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz not null default now(),
  ambassador_code_id bigint not null references public.ambassador_codes(id) on delete cascade,
  code               text not null,
  order_ref          text not null,
  customer_email     text,
  amount_eur         numeric not null check (amount_eur > 0),
  reversed_at        timestamptz,
  notes              text
);

create unique index if not exists idx_ambassador_wallet_spends_order_ref
  on public.ambassador_wallet_spends (upper(order_ref));

create index if not exists idx_ambassador_wallet_spends_code_id
  on public.ambassador_wallet_spends (ambassador_code_id);

alter table public.ambassador_wallet_spends enable row level security;

drop policy if exists "ambassador_wallet_spends_admin_select" on public.ambassador_wallet_spends;
create policy "ambassador_wallet_spends_admin_select"
  on public.ambassador_wallet_spends
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.b2b_admins a
      where lower(a.email) = lower(auth.email())
    )
  );

-- Replace redeem RPC to persist commission_amount_eur for each redemption.
create or replace function public.redeem_ambassador_code(
  p_code            text,
  p_order_ref       text,
  p_customer_email  text,
  p_discount_amount numeric,
  p_order_total     numeric
)
returns numeric
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id        bigint;
  v_pct       numeric;
  v_name      text;
  v_comm_pct  numeric;
  v_comm_eur  numeric;
begin
  select id, discount_pct, ambassador_name, commission_pct
    into v_id, v_pct, v_name, v_comm_pct
  from public.ambassador_codes
  where upper(code) = upper(trim(p_code))
    and active = true
    and (expires_at is null or expires_at > now())
    and (max_redemptions is null or redemption_count < max_redemptions)
  for update;

  if v_id is null then
    return null;
  end if;

  update public.ambassador_codes
     set redemption_count = redemption_count + 1
   where id = v_id;

  v_comm_eur := round(coalesce(p_order_total, 0) * coalesce(v_comm_pct, 0) / 100, 2);

  insert into public.ambassador_redemptions
    (code, ambassador_name, order_ref, customer_email, discount_pct, discount_amount_eur, order_total_eur, commission_amount_eur)
  values
    (upper(trim(p_code)), v_name, p_order_ref, p_customer_email, v_pct, p_discount_amount, p_order_total, v_comm_eur);

  return v_pct;
end;
$$;

grant execute on function public.redeem_ambassador_code(text, text, text, numeric, numeric) to anon, authenticated;

-- Returns one row for the authenticated ambassador account, or no rows when the
-- signed-in user is not an ambassador.
create or replace function public.get_my_ambassador_wallet()
returns table (
  code text,
  ambassador_name text,
  available_eur numeric,
  earned_eur numeric,
  spent_eur numeric,
  commission_pct numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text;
begin
  v_email := lower(trim(coalesce(auth.email(), '')));
  if v_email = '' then
    return;
  end if;

  return query
  with me as (
    select c.id, c.code, c.ambassador_name, c.commission_pct
    from public.ambassador_codes c
    where lower(coalesce(c.ambassador_email, '')) = v_email
      and c.active = true
    order by c.id desc
    limit 1
  ),
  earned as (
    select
      coalesce(sum(
        coalesce(r.commission_amount_eur, round(coalesce(r.order_total_eur, 0) * coalesce(m.commission_pct, 0) / 100, 2))
      ), 0)::numeric as total
    from me m
    left join public.ambassador_redemptions r on upper(r.code) = upper(m.code)
  ),
  spent as (
    select coalesce(sum(s.amount_eur), 0)::numeric as total
    from me m
    left join public.ambassador_wallet_spends s
      on s.ambassador_code_id = m.id
     and s.reversed_at is null
  )
  select
    m.code,
    m.ambassador_name,
    greatest(0, round(e.total - s.total, 2)) as available_eur,
    round(e.total, 2) as earned_eur,
    round(s.total, 2) as spent_eur,
    m.commission_pct
  from me m
  cross join earned e
  cross join spent s;
end;
$$;

grant execute on function public.get_my_ambassador_wallet() to authenticated;

-- Deducts ambassador wallet credit for the signed-in ambassador.
-- Idempotent per order_ref (reusing the same order_ref returns the existing spend).
create or replace function public.spend_my_ambassador_wallet(
  p_order_ref text,
  p_customer_email text,
  p_amount numeric
)
returns table (
  applied_amount_eur numeric,
  available_after_eur numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text;
  v_code_id bigint;
  v_code text;
  v_comm_pct numeric;
  v_earned numeric;
  v_spent numeric;
  v_available numeric;
  v_existing_amount numeric;
begin
  v_email := lower(trim(coalesce(auth.email(), '')));
  if v_email = '' then
    raise exception 'Authentication required';
  end if;
  if p_amount is null or p_amount <= 0 then
    raise exception 'Invalid wallet amount';
  end if;
  if trim(coalesce(p_order_ref, '')) = '' then
    raise exception 'Order reference is required';
  end if;

  select c.id, c.code, c.commission_pct
    into v_code_id, v_code, v_comm_pct
  from public.ambassador_codes c
  where lower(coalesce(c.ambassador_email, '')) = v_email
    and c.active = true
  order by c.id desc
  limit 1
  for update;

  if v_code_id is null then
    raise exception 'No active ambassador wallet found';
  end if;

  select s.amount_eur
    into v_existing_amount
  from public.ambassador_wallet_spends s
  where upper(s.order_ref) = upper(trim(p_order_ref))
    and s.ambassador_code_id = v_code_id
    and s.reversed_at is null
  limit 1;

  if v_existing_amount is not null then
    return query
    select
      round(v_existing_amount, 2) as applied_amount_eur,
      round(greatest(0, (
        coalesce((
          select sum(
            coalesce(r.commission_amount_eur, round(coalesce(r.order_total_eur, 0) * coalesce(v_comm_pct, 0) / 100, 2))
          )
          from public.ambassador_redemptions r
          where upper(r.code) = upper(v_code)
        ), 0)
        - coalesce((
          select sum(ws.amount_eur)
          from public.ambassador_wallet_spends ws
          where ws.ambassador_code_id = v_code_id
            and ws.reversed_at is null
        ), 0)
      )), 2) as available_after_eur;
    return;
  end if;

  select coalesce(sum(
           coalesce(r.commission_amount_eur, round(coalesce(r.order_total_eur, 0) * coalesce(v_comm_pct, 0) / 100, 2))
         ), 0)
    into v_earned
  from public.ambassador_redemptions r
  where upper(r.code) = upper(v_code);

  select coalesce(sum(s.amount_eur), 0)
    into v_spent
  from public.ambassador_wallet_spends s
  where s.ambassador_code_id = v_code_id
    and s.reversed_at is null;

  v_available := round(greatest(0, v_earned - v_spent), 2);
  if round(p_amount, 2) > v_available then
    raise exception 'Requested wallet amount exceeds available balance';
  end if;

  insert into public.ambassador_wallet_spends (
    ambassador_code_id,
    code,
    order_ref,
    customer_email,
    amount_eur
  ) values (
    v_code_id,
    v_code,
    trim(p_order_ref),
    nullif(trim(coalesce(p_customer_email, '')), ''),
    round(p_amount, 2)
  );

  return query
  select
    round(p_amount, 2) as applied_amount_eur,
    round(greatest(0, v_available - round(p_amount, 2)), 2) as available_after_eur;
end;
$$;

grant execute on function public.spend_my_ambassador_wallet(text, text, numeric) to authenticated;

-- Reverses a wallet spend when checkout fails after wallet deduction.
create or replace function public.rollback_my_ambassador_wallet_spend(
  p_order_ref text
)
returns numeric
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text;
  v_code_id bigint;
  v_amount numeric;
begin
  v_email := lower(trim(coalesce(auth.email(), '')));
  if v_email = '' then
    raise exception 'Authentication required';
  end if;
  if trim(coalesce(p_order_ref, '')) = '' then
    raise exception 'Order reference is required';
  end if;

  select c.id
    into v_code_id
  from public.ambassador_codes c
  where lower(coalesce(c.ambassador_email, '')) = v_email
  order by c.id desc
  limit 1;

  if v_code_id is null then
    return 0;
  end if;

  update public.ambassador_wallet_spends s
     set reversed_at = now(),
         notes = coalesce(s.notes || ' | ', '') || 'Auto-reversed after checkout failure'
   where s.ambassador_code_id = v_code_id
     and upper(s.order_ref) = upper(trim(p_order_ref))
     and s.reversed_at is null
  returning s.amount_eur into v_amount;

  return coalesce(v_amount, 0);
end;
$$;

grant execute on function public.rollback_my_ambassador_wallet_spend(text) to authenticated;
