-- Applications from nail artists who want to become a GEL.IT.UP® ambassador.
-- A row is inserted client-side when someone submits the form on /ambassadors.
-- Run once in the Supabase SQL Editor.

create table if not exists public.ambassador_applications (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  full_name   text        not null,
  email       text        not null,
  instagram   text        not null,
  tiktok      text,
  followers   text,
  country     text,
  message     text,
  status      text        not null default 'new',  -- new | reviewing | approved | rejected
  reviewed_at timestamptz,                          -- set by the admin approval workflow
  reviewed_by text
);

-- One application per Instagram handle keeps the review list clean.
create unique index if not exists idx_ambassador_applications_instagram
  on public.ambassador_applications (lower(instagram));

alter table public.ambassador_applications enable row level security;

-- Anyone (anon or authenticated) can INSERT so the public form always works.
drop policy if exists "ambassador_applications_insert_anon" on public.ambassador_applications;
create policy "ambassador_applications_insert_anon"
  on public.ambassador_applications
  for insert
  to anon, authenticated
  with check (true);

-- Only admins can SELECT (review incoming applications).
drop policy if exists "ambassador_applications_select_admin" on public.ambassador_applications;
create policy "ambassador_applications_select_admin"
  on public.ambassador_applications
  for select
  to authenticated
  using (
    exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email()))
  );
