-- Email signups for "notify me" campaign teasers (e.g. Winter Vault reveal countdown).
-- A row is inserted client-side when a visitor subscribes to be notified.
-- Run once in the Supabase SQL Editor.

create table if not exists public.vault_subscribers (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email      text        not null,
  campaign   text        not null default 'winter-vault-reveal'
);

create unique index if not exists idx_vault_subscribers_email_campaign
  on public.vault_subscribers (lower(email), campaign);

alter table public.vault_subscribers enable row level security;

-- Anyone (anon or authenticated) can INSERT so the subscribe form always works.
drop policy if exists "vault_subscribers_insert_anon" on public.vault_subscribers;
create policy "vault_subscribers_insert_anon"
  on public.vault_subscribers
  for insert
  to anon, authenticated
  with check (true);

-- Only admins can SELECT (export the list for the actual email send).
drop policy if exists "vault_subscribers_select_admin" on public.vault_subscribers;
create policy "vault_subscribers_select_admin"
  on public.vault_subscribers
  for select
  to authenticated
  using (
    exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email()))
  );
