create table if not exists public.b2b_products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sku text not null unique,
  name text not null,
  description text,
  category text,
  hex_color text,
  price_wholesale numeric(12,2),
  currency text default 'EUR',
  stock_qty integer default 0,
  is_active boolean not null default true,
  image_url text,
  source text default 'gelitup.gr',
  external_id text,
  metadata jsonb default '{}'::jsonb
);

create index if not exists idx_b2b_products_category on public.b2b_products (category);
create index if not exists idx_b2b_products_active on public.b2b_products (is_active);

create or replace function public.set_b2b_products_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_b2b_products_updated_at on public.b2b_products;
create trigger trg_b2b_products_updated_at
before update on public.b2b_products
for each row
execute function public.set_b2b_products_updated_at();

alter table public.b2b_products enable row level security;

drop policy if exists "b2b_products_select" on public.b2b_products;
create policy "b2b_products_select"
on public.b2b_products
for select
to anon, authenticated
using (is_active = true);
