-- Ambassador discount codes for the B2C storefront checkout.
-- Each ambassador is allocated an individual code they share with their clients.
-- Codes are validated + redeemed through SECURITY DEFINER RPCs so the anon key
-- can check/redeem a code WITHOUT being able to read the whole codes table.
-- Run once in the Supabase SQL Editor.

-- ── Codes ──────────────────────────────────────────────────────────────────
create table if not exists public.ambassador_codes (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  code             text        not null,
  ambassador_name  text,
  ambassador_email text,
  discount_pct     numeric     not null default 20 check (discount_pct >= 0 and discount_pct <= 100),
  commission_pct   numeric     not null default 20 check (commission_pct >= 0 and commission_pct <= 100),
  active           boolean     not null default true,
  expires_at       timestamptz,                        -- null = never expires
  max_redemptions  integer,                            -- null = unlimited
  redemption_count integer     not null default 0,
  notes            text
);

-- One code value regardless of case ("maria20" == "MARIA20").
create unique index if not exists idx_ambassador_codes_code
  on public.ambassador_codes (upper(code));

-- ── Redemptions (attribution / commission log) ─────────────────────────────
create table if not exists public.ambassador_redemptions (
  id                  bigint generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  code                text        not null,
  ambassador_name     text,
  order_ref           text,
  customer_email      text,
  discount_pct        numeric,
  discount_amount_eur numeric,
  order_total_eur     numeric
);

alter table public.ambassador_codes enable row level security;
alter table public.ambassador_redemptions enable row level security;

-- No anon SELECT policy on the codes table on purpose — validation goes through
-- the RPC below so codes cannot be enumerated with the public anon key.

-- Admins (b2b_admins) can manage codes and read redemptions.
drop policy if exists "ambassador_codes_admin_all" on public.ambassador_codes;
create policy "ambassador_codes_admin_all"
  on public.ambassador_codes
  for all
  to authenticated
  using (exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email())))
  with check (exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email())));

drop policy if exists "ambassador_redemptions_admin_select" on public.ambassador_redemptions;
create policy "ambassador_redemptions_admin_select"
  on public.ambassador_redemptions
  for select
  to authenticated
  using (exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email())));

-- ── validate_ambassador_code(code) → { code, ambassador_name, discount_pct } ─
-- Returns a single row when the code is active, not expired, and under its
-- redemption cap; returns no rows otherwise. Called at checkout when the
-- customer clicks "Apply".
create or replace function public.validate_ambassador_code(p_code text)
returns table (code text, ambassador_name text, discount_pct numeric)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  select c.code, c.ambassador_name, c.discount_pct
  from public.ambassador_codes c
  where upper(c.code) = upper(trim(p_code))
    and c.active = true
    and (c.expires_at is null or c.expires_at > now())
    and (c.max_redemptions is null or c.redemption_count < c.max_redemptions)
  limit 1;
end;
$$;

grant execute on function public.validate_ambassador_code(text) to anon, authenticated;

-- ── redeem_ambassador_code(...) → discount_pct | null ───────────────────────
-- Atomically increments the redemption counter and logs a redemption row for
-- attribution. Returns the discount_pct if the code was valid, else null.
-- Called once, after the order is successfully placed.
create or replace function public.redeem_ambassador_code(
  p_code            text,
  p_order_ref       text,
  p_customer_email  text,
  p_discount_amount numeric,
  p_order_total     numeric
)
returns numeric
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id   bigint;
  v_pct  numeric;
  v_name text;
begin
  select id, discount_pct, ambassador_name
    into v_id, v_pct, v_name
  from public.ambassador_codes
  where upper(code) = upper(trim(p_code))
    and active = true
    and (expires_at is null or expires_at > now())
    and (max_redemptions is null or redemption_count < max_redemptions)
  for update;

  if v_id is null then
    return null;
  end if;

  update public.ambassador_codes
     set redemption_count = redemption_count + 1
   where id = v_id;

  insert into public.ambassador_redemptions
    (code, ambassador_name, order_ref, customer_email, discount_pct, discount_amount_eur, order_total_eur)
  values
    (upper(trim(p_code)), v_name, p_order_ref, p_customer_email, v_pct, p_discount_amount, p_order_total);

  return v_pct;
end;
$$;

grant execute on function public.redeem_ambassador_code(text, text, text, numeric, numeric) to anon, authenticated;

-- ── Example seed (uncomment + edit to allocate an ambassador a code) ────────
-- insert into public.ambassador_codes (code, ambassador_name, ambassador_email, discount_pct)
--   values ('MARIA20', 'Maria Example', 'maria@example.com', 20);
