-- Persistent votes for the Winter Vault "vote for the next revival" poll.
-- One row per vote; voter_key is a random per-browser UUID (no PII) used to
-- de-duplicate. Displayed counts = seed numbers in the page + these rows.
-- Run once in the Supabase SQL Editor.

create table if not exists public.vault_votes (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  shade_code text        not null,
  voter_key  text        not null,
  campaign   text        not null default 'winter-vault-revival'
);

create unique index if not exists idx_vault_votes_shade_voter
  on public.vault_votes (shade_code, voter_key);

alter table public.vault_votes enable row level security;

-- Anyone can INSERT a vote (anonymous voting, no registration).
drop policy if exists "vault_votes_insert_anon" on public.vault_votes;
create policy "vault_votes_insert_anon"
  on public.vault_votes
  for insert
  to anon, authenticated
  with check (true);

-- Anyone can SELECT so the page can show live counts (rows contain no PII).
drop policy if exists "vault_votes_select_anon" on public.vault_votes;
create policy "vault_votes_select_anon"
  on public.vault_votes
  for select
  to anon, authenticated
  using (true);
