create table if not exists public.shipping_zones (
  country_code text primary key check (country_code ~ '^[A-Z]{2}$'),
  country_name text not null,
  zone_code text not null check (zone_code ~ '^ZONE_[2-6]$'),
  zone_name text not null,
  -- Flat checkout fee used by the current checkout flow.
  -- Keep this for now (15/22 model) while weight-based logic is rolled out.
  checkout_flat_fee_eur numeric(12,2) check (checkout_flat_fee_eur >= 0),
  is_checkout_enabled boolean not null default false,
  redirect_checkout boolean not null default false,
  redirect_url text,
  redirect_message text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_shipping_zones_zone_code on public.shipping_zones (zone_code);
create index if not exists idx_shipping_zones_checkout_enabled on public.shipping_zones (is_checkout_enabled);
create index if not exists idx_shipping_zones_active on public.shipping_zones (is_active);

create table if not exists public.shipping_zone_rates (
  id bigint generated by default as identity primary key,
  zone_code text not null check (zone_code ~ '^ZONE_[2-6]$'),
  bracket_label text not null,
  weight_from_kg numeric(10,3) not null check (weight_from_kg >= 0),
  weight_to_kg numeric(10,3) not null check (weight_to_kg > weight_from_kg),
  price_eur numeric(12,2) not null check (price_eur >= 0),
  price_bgn numeric(12,2) check (price_bgn >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (zone_code, weight_from_kg, weight_to_kg)
);

create index if not exists idx_shipping_zone_rates_zone_code on public.shipping_zone_rates (zone_code);
create index if not exists idx_shipping_zone_rates_active on public.shipping_zone_rates (is_active);

create or replace function public.set_shipping_tables_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_shipping_zones_updated_at on public.shipping_zones;
create trigger trg_shipping_zones_updated_at
before update on public.shipping_zones
for each row
execute function public.set_shipping_tables_updated_at();

drop trigger if exists trg_shipping_zone_rates_updated_at on public.shipping_zone_rates;
create trigger trg_shipping_zone_rates_updated_at
before update on public.shipping_zone_rates
for each row
execute function public.set_shipping_tables_updated_at();

alter table public.shipping_zones enable row level security;
alter table public.shipping_zone_rates enable row level security;

drop policy if exists "shipping_zones_select_active" on public.shipping_zones;
create policy "shipping_zones_select_active"
on public.shipping_zones
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "shipping_zone_rates_select_active" on public.shipping_zone_rates;
create policy "shipping_zone_rates_select_active"
on public.shipping_zone_rates
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "shipping_zones_admin_insert" on public.shipping_zones;
create policy "shipping_zones_admin_insert"
on public.shipping_zones
for insert
to authenticated
with check (
  exists (
    select 1
    from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
);

drop policy if exists "shipping_zones_admin_update" on public.shipping_zones;
create policy "shipping_zones_admin_update"
on public.shipping_zones
for update
to authenticated
using (
  exists (
    select 1
    from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
)
with check (
  exists (
    select 1
    from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
);

drop policy if exists "shipping_zones_admin_delete" on public.shipping_zones;
create policy "shipping_zones_admin_delete"
on public.shipping_zones
for delete
to authenticated
using (
  exists (
    select 1
    from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
);

drop policy if exists "shipping_zone_rates_admin_insert" on public.shipping_zone_rates;
create policy "shipping_zone_rates_admin_insert"
on public.shipping_zone_rates
for insert
to authenticated
with check (
  exists (
    select 1
    from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
);

drop policy if exists "shipping_zone_rates_admin_update" on public.shipping_zone_rates;
create policy "shipping_zone_rates_admin_update"
on public.shipping_zone_rates
for update
to authenticated
using (
  exists (
    select 1
    from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
)
with check (
  exists (
    select 1
    from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
);

drop policy if exists "shipping_zone_rates_admin_delete" on public.shipping_zone_rates;
create policy "shipping_zone_rates_admin_delete"
on public.shipping_zone_rates
for delete
to authenticated
using (
  exists (
    select 1
    from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
);

insert into public.shipping_zone_rates
  (zone_code, bracket_label, weight_from_kg, weight_to_kg, price_eur, price_bgn)
values
  ('ZONE_2', 'to_5kg',     0,  5, 18.41,  36.00),
  ('ZONE_2', 'from_5_to_10kg',  5, 10, 21.47,  42.00),
  ('ZONE_2', 'from_10_to_20kg', 10, 20, 24.54,  48.00),
  ('ZONE_2', 'from_20_to_30kg', 20, 30, 27.61,  54.00),
  ('ZONE_2', 'from_30_to_40kg', 30, 40, 44.18,  86.40),
  ('ZONE_3', 'to_5kg',     0,  5, 24.54,  48.00),
  ('ZONE_3', 'from_5_to_10kg',  5, 10, 30.68,  60.00),
  ('ZONE_3', 'from_10_to_20kg', 10, 20, 36.82,  72.00),
  ('ZONE_3', 'from_20_to_30kg', 20, 30, 42.96,  84.00),
  ('ZONE_3', 'from_30_to_40kg', 30, 40, 51.54, 100.80),
  ('ZONE_4', 'to_5kg',     0,  5, 30.68,  60.00),
  ('ZONE_4', 'from_5_to_10kg',  5, 10, 36.82,  72.00),
  ('ZONE_4', 'from_10_to_20kg', 10, 20, 42.95,  84.00),
  ('ZONE_4', 'from_20_to_30kg', 20, 30, 49.08,  96.00),
  ('ZONE_4', 'from_30_to_40kg', 30, 40, 61.36, 120.00),
  ('ZONE_5', 'to_5kg',     0,  5, 36.82,  72.00),
  ('ZONE_5', 'from_5_to_10kg',  5, 10, 46.02,  90.00),
  ('ZONE_5', 'from_10_to_20kg', 10, 20, 52.15, 102.00),
  ('ZONE_5', 'from_20_to_30kg', 20, 30, 58.29, 114.00),
  ('ZONE_5', 'from_30_to_40kg', 30, 40, 73.63, 144.00),
  ('ZONE_6', 'to_5kg',     0,  5, 30.68,  60.00),
  ('ZONE_6', 'from_5_to_10kg',  5, 10, 38.35,  75.00),
  ('ZONE_6', 'from_10_to_20kg', 10, 20, 46.02,  90.00),
  ('ZONE_6', 'from_20_to_30kg', 20, 30, 53.69, 105.00),
  ('ZONE_6', 'from_30_to_40kg', 30, 40, 61.36, 120.00)
on conflict (zone_code, weight_from_kg, weight_to_kg) do update set
  bracket_label = excluded.bracket_label,
  price_eur = excluded.price_eur,
  price_bgn = excluded.price_bgn,
  is_active = true;

insert into public.shipping_zones
  (country_code, country_name, zone_code, zone_name, checkout_flat_fee_eur, is_checkout_enabled, redirect_checkout, redirect_url, redirect_message, is_active)
values
  -- Keep current live checkout behavior (€15 zone)
  ('AT', 'Austria', 'ZONE_2', 'Zone 2', 15.00, true, false, null, null, true),
  ('DE', 'Germany', 'ZONE_2', 'Zone 2', 15.00, true, false, null, null, true),
  ('HU', 'Hungary', 'ZONE_2', 'Zone 2', 15.00, true, false, null, null, true),
  ('BE', 'Belgium', 'ZONE_3', 'Zone 3', 15.00, true, false, null, null, true),
  ('NL', 'Netherlands', 'ZONE_3', 'Zone 3', 15.00, true, false, null, null, true),
  ('PL', 'Poland', 'ZONE_3', 'Zone 3', 15.00, true, false, null, null, true),
  ('SK', 'Slovakia', 'ZONE_3', 'Zone 3', 15.00, true, false, null, null, true),
  ('SI', 'Slovenia', 'ZONE_3', 'Zone 3', 15.00, true, false, null, null, true),
  ('HR', 'Croatia', 'ZONE_3', 'Zone 3', 15.00, true, false, null, null, true),
  ('CZ', 'Czech Republic', 'ZONE_3', 'Zone 3', 15.00, true, false, null, null, true),

  -- Keep current live checkout behavior (€22 zone)
  ('DK', 'Denmark', 'ZONE_4', 'Zone 4', 22.00, true, false, null, null, true),
  ('ES', 'Spain', 'ZONE_4', 'Zone 4', 22.00, true, false, null, null, true),
  ('LU', 'Luxembourg', 'ZONE_4', 'Zone 4', 22.00, true, false, null, null, true),
  ('EE', 'Estonia', 'ZONE_5', 'Zone 5', 22.00, true, false, null, null, true),
  ('IE', 'Ireland', 'ZONE_5', 'Zone 5', 22.00, true, false, null, null, true),
  ('LV', 'Latvia', 'ZONE_5', 'Zone 5', 22.00, true, false, null, null, true),
  ('LT', 'Lithuania', 'ZONE_5', 'Zone 5', 22.00, true, false, null, null, true),
  ('PT', 'Portugal', 'ZONE_5', 'Zone 5', 22.00, true, false, null, null, true),
  ('FI', 'Finland', 'ZONE_5', 'Zone 5', 22.00, true, false, null, null, true),
  ('SE', 'Sweden', 'ZONE_5', 'Zone 5', 22.00, true, false, null, null, true),
  ('NO', 'Norway', 'ZONE_6', 'Zone 6', 22.00, true, false, null, null, true),
  ('CH', 'Switzerland', 'ZONE_6', 'Zone 6', 22.00, true, false, null, null, true),
  ('GB', 'United Kingdom', 'ZONE_6', 'Zone 6', 22.00, true, false, null, null, true),

  -- Distributor handoff countries (capture lead, route purchase to local site)
  ('IT', 'Italy', 'ZONE_3', 'Zone 3', null, false, true, 'https://www.gelitup.it', 'For Italy orders, please continue on GEL.IT.UP Italy.', true),
  ('GR', 'Greece', 'ZONE_5', 'Zone 5', null, false, true, 'https://gelitup.gr', 'For Greece orders, please continue on GEL.IT.UP Greece.', true),
  ('BG', 'Bulgaria', 'ZONE_2', 'Zone 2', null, false, true, 'https://gelitup.bg', 'For Bulgaria orders, please continue on GEL.IT.UP Bulgaria.', true),

  -- Tracked from carrier sheet but intentionally not enabled in current checkout
  ('FR', 'France', 'ZONE_3', 'Zone 3', null, false, false, null, null, true),
  ('XI', 'Northern Ireland', 'ZONE_5', 'Zone 5', null, false, false, null, null, true)
on conflict (country_code) do update set
  country_name = excluded.country_name,
  zone_code = excluded.zone_code,
  zone_name = excluded.zone_name,
  checkout_flat_fee_eur = excluded.checkout_flat_fee_eur,
  is_checkout_enabled = excluded.is_checkout_enabled,
  redirect_checkout = excluded.redirect_checkout,
  redirect_url = excluded.redirect_url,
  redirect_message = excluded.redirect_message,
  is_active = excluded.is_active;
