-- Login issue tracking table.
-- A row is inserted client-side whenever a known client fails to sign in,
-- so admins can see who is having trouble and reach out proactively.
-- Run once in the Supabase SQL Editor.

create table if not exists public.b2b_login_issues (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  email       text        not null,
  issue_type  text        not null,  -- 'pending_approval' | 'rejected' | 'bad_password' | 'unexpected_error' | 'login_blocked'
  message     text,
  resolved    boolean     not null default false,
  resolved_at timestamptz,
  resolved_by text
);

create index if not exists idx_b2b_login_issues_email    on public.b2b_login_issues (email);
create index if not exists idx_b2b_login_issues_resolved on public.b2b_login_issues (resolved);
create index if not exists idx_b2b_login_issues_created  on public.b2b_login_issues (created_at desc);

alter table public.b2b_login_issues enable row level security;

-- Anyone (anon or authenticated) can INSERT so failed logins are always captured.
drop policy if exists "login_issues_insert_anon" on public.b2b_login_issues;
create policy "login_issues_insert_anon"
  on public.b2b_login_issues
  for insert
  to anon, authenticated
  with check (true);

-- Only admins can SELECT.
drop policy if exists "login_issues_select_admin" on public.b2b_login_issues;
create policy "login_issues_select_admin"
  on public.b2b_login_issues
  for select
  to authenticated
  using (
    exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email()))
  );

-- Only admins can UPDATE (to mark resolved).
drop policy if exists "login_issues_update_admin" on public.b2b_login_issues;
create policy "login_issues_update_admin"
  on public.b2b_login_issues
  for update
  to authenticated
  using (
    exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email()))
  )
  with check (
    exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email()))
  );

-- Only admins can DELETE.
drop policy if exists "login_issues_delete_admin" on public.b2b_login_issues;
create policy "login_issues_delete_admin"
  on public.b2b_login_issues
  for delete
  to authenticated
  using (
    exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email()))
  );
