-- Applications from nail professionals (distributors, educators, nail masters/
-- ambassadors, salons & studios) who want to work with GEL.IT.UP worldwide.
-- A row is inserted client-side when someone submits the form on /work-with-us.
-- Run once in the Supabase SQL Editor.

create table if not exists public.work_with_us_applications (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  first_name      text        not null,
  surname         text        not null,
  email           text        not null,
  phone_dial_code text,
  phone_number    text        not null,
  instagram_handle text,
  instagram_url    text,
  tiktok_handle    text,
  tiktok_url       text,
  country         text        not null,
  roles           text[]      not null default '{}',
  roles_other     text,
  why_interested  text        not null,
  value_add       text        not null,
  what_offer      text        not null,
  consent         boolean     not null default false,
  source          text,
  status          text        not null default 'new',  -- new | reviewing | contacted | approved | rejected
  reviewed_at     timestamptz,
  reviewed_by     text,
  admin_comment   text
);

create index if not exists idx_work_with_us_applications_email on public.work_with_us_applications (lower(email));
create index if not exists idx_work_with_us_applications_status on public.work_with_us_applications (status);

alter table public.work_with_us_applications enable row level security;

-- Anyone (anon or authenticated) can INSERT so the public form always works.
drop policy if exists "work_with_us_applications_insert_anon" on public.work_with_us_applications;
create policy "work_with_us_applications_insert_anon"
  on public.work_with_us_applications
  for insert
  to anon, authenticated
  with check (true);

-- Only admins can SELECT (review incoming applications).
drop policy if exists "work_with_us_applications_select_admin" on public.work_with_us_applications;
create policy "work_with_us_applications_select_admin"
  on public.work_with_us_applications
  for select
  to authenticated
  using (
    exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email()))
  );

-- Admins can UPDATE (status, admin_comment, reviewed_* fields) while reviewing.
drop policy if exists "work_with_us_applications_update_admin" on public.work_with_us_applications;
create policy "work_with_us_applications_update_admin"
  on public.work_with_us_applications
  for update
  to authenticated
  using (
    exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email()))
  )
  with check (
    exists (select 1 from public.b2b_admins a where lower(a.email) = lower(auth.email()))
  );
