create table if not exists public.b2b_registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_type text not null default 'company',
  company_name text not null,
  vat_number text not null,
  contact_name text not null,
  contact_email text not null,
  phone text not null,
  website text,
  shipping_type text not null default 'road',
  address text not null,
  city text not null,
  postal_code text not null,
  country text not null,
  invoice_address_line1 text,
  invoice_address_line2 text,
  invoice_area text,
  invoice_region text,
  invoice_country text,
  invoice_postal_code text,
  shipping_same_as_invoice boolean not null default true,
  shipping_name text,
  shipping_phone text,
  shipping_address_line1 text,
  shipping_address_line2 text,
  shipping_area text,
  shipping_region text,
  shipping_country text,
  shipping_postal_code text,
  business_type text not null,
  notes text,
  application_type text not null default 'distributor',
  order_profile text,
  admin_comment text,
  order_action text,
  order_payment_status text,
  order_shipping_status text,
  tracking_number text,
  tracking_url text,
  action_updated_at timestamptz,
  action_updated_by text,
  status text not null default 'pending',
  reviewed_at timestamptz,
  reviewed_by text
);

alter table public.b2b_registrations add column if not exists customer_type text not null default 'company';
alter table public.b2b_registrations add column if not exists shipping_type text not null default 'road';
alter table public.b2b_registrations add column if not exists invoice_address_line1 text;
alter table public.b2b_registrations add column if not exists invoice_address_line2 text;
alter table public.b2b_registrations add column if not exists invoice_area text;
alter table public.b2b_registrations add column if not exists invoice_region text;
alter table public.b2b_registrations add column if not exists invoice_country text;
alter table public.b2b_registrations add column if not exists invoice_postal_code text;
alter table public.b2b_registrations add column if not exists shipping_same_as_invoice boolean not null default true;
alter table public.b2b_registrations add column if not exists shipping_name text;
alter table public.b2b_registrations add column if not exists shipping_phone text;
alter table public.b2b_registrations add column if not exists shipping_address_line1 text;
alter table public.b2b_registrations add column if not exists shipping_address_line2 text;
alter table public.b2b_registrations add column if not exists shipping_area text;
alter table public.b2b_registrations add column if not exists shipping_region text;
alter table public.b2b_registrations add column if not exists shipping_country text;
alter table public.b2b_registrations add column if not exists shipping_postal_code text;
alter table public.b2b_registrations add column if not exists application_type text not null default 'distributor';
alter table public.b2b_registrations add column if not exists order_profile text;
alter table public.b2b_registrations add column if not exists admin_comment text;
alter table public.b2b_registrations add column if not exists order_action text;
alter table public.b2b_registrations add column if not exists order_payment_status text;
alter table public.b2b_registrations add column if not exists order_shipping_status text;
alter table public.b2b_registrations add column if not exists tracking_number text;
alter table public.b2b_registrations add column if not exists tracking_url text;
alter table public.b2b_registrations add column if not exists action_updated_at timestamptz;
alter table public.b2b_registrations add column if not exists action_updated_by text;

create table if not exists public.b2b_admins (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null unique
);

create index if not exists idx_b2b_registrations_contact_email on public.b2b_registrations (contact_email);
create index if not exists idx_b2b_registrations_status on public.b2b_registrations (status);

alter table public.b2b_registrations enable row level security;
alter table public.b2b_admins enable row level security;

drop policy if exists "b2b_registrations_insert_anon" on public.b2b_registrations;
create policy "b2b_registrations_insert_anon"
on public.b2b_registrations
for insert
to anon, authenticated
with check (true);

drop policy if exists "b2b_registrations_select_own" on public.b2b_registrations;
create policy "b2b_registrations_select_own"
on public.b2b_registrations
for select
to authenticated
using (lower(contact_email) = lower(auth.email()));

drop policy if exists "b2b_registrations_select_admin" on public.b2b_registrations;
create policy "b2b_registrations_select_admin"
on public.b2b_registrations
for select
to authenticated
using (
  exists (
    select 1 from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
);

drop policy if exists "b2b_registrations_update_admin" on public.b2b_registrations;
create policy "b2b_registrations_update_admin"
on public.b2b_registrations
for update
to authenticated
using (
  exists (
    select 1 from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
)
with check (
  exists (
    select 1 from public.b2b_admins a
    where lower(a.email) = lower(auth.email())
  )
);

drop policy if exists "b2b_admins_select_self" on public.b2b_admins;
create policy "b2b_admins_select_self"
on public.b2b_admins
for select
to authenticated
using (lower(email) = lower(auth.email()));
