-- Guestbook / visitor comments
create table if not exists public.guestbook (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name       text        not null,
  country    text        not null,
  role       text        not null default 'Nail Technician',
  message    text        not null,
  approved   boolean     not null default false,
  featured   boolean     not null default false
);

alter table public.guestbook enable row level security;

-- Anyone (including anonymous visitors) can insert a comment
create policy "Anyone can submit a guestbook entry"
  on public.guestbook for insert to anon, authenticated
  with check (true);

-- Anyone can read approved entries
create policy "Anyone can read approved guestbook entries"
  on public.guestbook for select to anon, authenticated
  using (approved = true);

-- Authenticated admins can read ALL entries (for moderation)
create policy "Admins can read all guestbook entries"
  on public.guestbook for select to authenticated
  using (
    exists (select 1 from public.b2b_admins where email = auth.email())
  );

-- Authenticated admins can update entries (approve / reject / feature)
create policy "Admins can update guestbook entries"
  on public.guestbook for update to authenticated
  using (
    exists (select 1 from public.b2b_admins where email = auth.email())
  );

-- Authenticated admins can delete entries
create policy "Admins can delete guestbook entries"
  on public.guestbook for delete to authenticated
  using (
    exists (select 1 from public.b2b_admins where email = auth.email())
  );

