create table if not exists public.user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  product_code text,
  product_name text not null,
  image_url text,
  category text not null default '',
  created_at timestamptz not null default now()
);

create unique index if not exists user_favorites_unique
  on public.user_favorites (user_id, product_name);

alter table public.user_favorites enable row level security;

create policy "Users can view own favorites"
  on public.user_favorites
  for select
  using (auth.uid() = user_id);

create policy "Users can insert own favorites"
  on public.user_favorites
  for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own favorites"
  on public.user_favorites
  for delete
  using (auth.uid() = user_id);
