create table if not exists public.b2b_orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_email text,
  consignee_name text,
  consignee_phone text,
  shipping_address text,
  items jsonb not null,
  total_units integer not null,
  source text not null default 'portal',
  module text not null default 'solid-colours',
  status text not null default 'submitted'
);

alter table public.b2b_orders
  add column if not exists consignee_name text,
  add column if not exists consignee_phone text,
  add column if not exists shipping_address text;

alter table public.b2b_orders enable row level security;

drop policy if exists "b2b_orders_insert_authenticated" on public.b2b_orders;
create policy "b2b_orders_insert_authenticated"
on public.b2b_orders
for insert
to authenticated
with check (true);

drop policy if exists "b2b_orders_select_own" on public.b2b_orders;
create policy "b2b_orders_select_own"
on public.b2b_orders
for select
to authenticated
using (customer_email = auth.email());

-- Admin policies — admins (listed in b2b_admins) can read, update, and delete all orders.
create policy if not exists "Admins can read all orders"
  on public.b2b_orders for select to authenticated
  using (exists (select 1 from public.b2b_admins where email = auth.email()));

create policy if not exists "Admins can update orders"
  on public.b2b_orders for update to authenticated
  using (exists (select 1 from public.b2b_admins where email = auth.email()));

create policy if not exists "Admins can delete orders"
  on public.b2b_orders for delete to authenticated
  using (exists (select 1 from public.b2b_admins where email = auth.email()));
